/*==============================================================================

 Copyright 2023 by Roland Rabien
 For more information visit www.rabiensoftware.com

 ==============================================================================*/

//==============================================================================

#pragma clang diagnostic ignored "-Wstrict-prototypes"
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wimplicit-int-conversion"
#pragma clang diagnostic ignored "-Wsign-conversion"
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wsign-compare"
#pragma clang diagnostic ignored "-Wshadow"
#pragma clang diagnostic ignored "-Wshorten-64-to-32"
#pragma clang diagnostic ignored "-Wshift-sign-overflow"
#pragma clang diagnostic ignored "-Wswitch-enum"
#pragma clang diagnostic ignored "-Wpointer-to-int-cast"
#pragma clang diagnostic ignored "-Wcast-align"
#pragma clang diagnostic ignored "-Wunused-but-set-variable"
#pragma clang diagnostic ignored "-Wabsolute-value"
#pragma clang diagnostic ignored "-Wcast-align"

#define FEATURE_SOUND

#include "source/doomgeneric/p_enemy.c"
#include "source/doomgeneric/p_floor.c"
#include "source/doomgeneric/p_inter.c"
#include "source/doomgeneric/p_lights.c"
#include "source/doomgeneric/p_map.c"
#include "source/doomgeneric/p_maputl.c"
#include "source/doomgeneric/p_mobj.c"
#include "source/doomgeneric/p_plats.c"
#include "source/doomgeneric/p_pspr.c"
#include "source/doomgeneric/p_saveg.c"
#include "source/doomgeneric/p_setup.c"
#include "source/doomgeneric/p_sight.c"
#include "source/doomgeneric/p_spec.c"
#include "source/doomgeneric/p_switch.c"
#include "source/doomgeneric/p_telept.c"
#include "source/doomgeneric/p_tick.c"
#include "source/doomgeneric/p_user.c"
#include "source/doomgeneric/r_bsp.c"
#include "source/doomgeneric/r_data.c"
#include "source/doomgeneric/r_draw.c"
#include "source/doomgeneric/r_main.c"
#include "source/doomgeneric/r_plane.c"
#include "source/doomgeneric/r_segs.c"
#include "source/doomgeneric/r_sky.c"
#include "source/doomgeneric/r_things.c"
#include "source/doomgeneric/s_sound.c"
#include "source/doomgeneric/sha1.c"
#include "source/doomgeneric/sounds.c"
#include "source/doomgeneric/st_lib.c"
#include "source/doomgeneric/st_stuff.c"
#include "source/doomgeneric/statdump.c"
#include "source/doomgeneric/tables.c"
#include "source/doomgeneric/v_video.c"
#include "source/doomgeneric/w_checksum.c"
#include "source/doomgeneric/w_file.c"
#include "source/doomgeneric/w_file_stdc.c"
#include "source/doomgeneric/w_main.c"
#include "source/doomgeneric/w_wad.c"
#include "source/doomgeneric/z_zone.c"
