/*==============================================================================

 Copyright 2023 by Roland Rabien
 For more information visit www.rabiensoftware.com

 ==============================================================================*/

//==============================================================================

#pragma clang diagnostic ignored "-Wstrict-prototypes"
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wimplicit-int-conversion"
#pragma clang diagnostic ignored "-Wsign-conversion"
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wsign-compare"
#pragma clang diagnostic ignored "-Wshadow"
#pragma clang diagnostic ignored "-Wshorten-64-to-32"
#pragma clang diagnostic ignored "-Wshift-sign-overflow"
#pragma clang diagnostic ignored "-Wswitch-enum"
#pragma clang diagnostic ignored "-Wpointer-to-int-cast"
#pragma clang diagnostic ignored "-Wcast-align"
#pragma clang diagnostic ignored "-Wunused-but-set-variable"
#pragma clang diagnostic ignored "-Wabsolute-value"
#pragma clang diagnostic ignored "-Wcast-align"

#define FEATURE_SOUND

#include "source/doomgeneric/am_map.c"
#include "source/doomgeneric/d_event.c"
#include "source/doomgeneric/d_items.c"
#include "source/doomgeneric/d_iwad.c"
#include "source/doomgeneric/d_loop.c"
#include "source/doomgeneric/d_main.c"
#include "source/doomgeneric/d_mode.c"
#include "source/doomgeneric/d_net.c"
#include "source/doomgeneric/doomdef.c"
#include "source/doomgeneric/doomgeneric.c"
#include "source/doomgeneric/doomstat.c"
#include "source/doomgeneric/dstrings.c"
#include "source/doomgeneric/dummy.c"
#include "source/doomgeneric/f_finale.c"
#include "source/doomgeneric/f_wipe.c"
#include "source/doomgeneric/g_game.c"
#include "source/doomgeneric/gusconf.c"
#include "source/doomgeneric/hu_lib.c"
#include "source/doomgeneric/hu_stuff.c"
#include "source/doomgeneric/i_cdmus.c"
#include "source/doomgeneric/i_endoom.c"
#include "source/doomgeneric/i_input.c"
#include "source/doomgeneric/i_joystick.c"
#include "source/doomgeneric/i_scale.c"
#include "source/doomgeneric/i_sound.c"
#include "source/doomgeneric/i_system.c"
#include "source/doomgeneric/i_timer.c"
#include "source/doomgeneric/icon.c"
#include "source/doomgeneric/info.c"
#include "source/doomgeneric/m_argv.c"
#include "source/doomgeneric/m_bbox.c"
#include "source/doomgeneric/m_cheat.c"
#include "source/doomgeneric/m_config.c"
#include "source/doomgeneric/m_controls.c"
#include "source/doomgeneric/m_fixed.c"
#include "source/doomgeneric/m_menu.c"
#include "source/doomgeneric/m_misc.c"
#include "source/doomgeneric/m_random.c"
#include "source/doomgeneric/memio.c"
#include "source/doomgeneric/mus2mid.c"
#include "source/doomgeneric/p_ceilng.c"
#include "source/doomgeneric/p_doors.c"

